'use strict';
(() => {
 const D=window.RESEARCH_DATA; const Guards=window.ResearchGuards;
 if(!D?.companies?.length||!D.sources||!Guards||!window.ResearchPanels||!window.MarketPanel){document.getElementById('fatal').hidden=false;return;}
 const $=id=>document.getElementById(id);
 const esc=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 const safeURL=raw=>{try{const u=new URL(raw);return u.protocol==='https:'?u.href:null;}catch{return null;}};
 const lists=items=>'<ul>'+items.map(x=>'<li>'+esc(x)+'</li>').join('')+'</ul>';
 const date=iso=>{try{return new Date(iso).toLocaleString('zh-CN',{hour12:false});}catch{return iso;}};
 const baseline=JSON.parse(JSON.stringify(D));
 const states=new Map();let selected=D.companies[0].id,tab='evidence',view='companies',apiStatus=null,history=[],storeError='',eventId=D.events[0].id;
 const STORE='robot-evidence-history-v2';
 try{const stored=JSON.parse(localStorage.getItem(STORE)||'[]');if(!Array.isArray(stored))throw Error();history=stored.filter(v=>Guards.version(v)&&D.companies.some(c=>c.id===v.companyId)).slice(-30);for(const v of history){Object.assign(D.companies.find(c=>c.id===v.companyId),v.patch);D.sources[v.source.id]=v.source;}}catch{storeError='暂时无法读取你的记录，先为你展示原有资料。';}
 $('app').hidden=false;
 const company=id=>D.companies.find(c=>c.id===id);
 const stageRanks={revenue:6,delivery:5,validation:4,research:3,capability:3,statement:2,insufficient:1};
 function reportPeriod(source){const t=source?.title||'';let m;if((m=t.match(/(20\d{2})年(\d{1,2})月/)))return Number(m[1])*100+Number(m[2]);if((m=t.match(/(20\d{2})年.*半年度/)))return Number(m[1])*100+6;if((m=t.match(/(20\d{2})年.*年度/)))return Number(m[1])*100+12;if((m=t.match(/Q([1-4])\s*(20\d{2})/i)))return Number(m[2])*100+Number(m[1])*3;return null;}
 function mayUpgrade(c,r,f){if(!f)return false;const incoming=reportPeriod(r.source);const prior=Math.max(0,...c.evidence.map(e=>reportPeriod(D.sources[e.source])||0));if(incoming&&prior&&incoming<prior)return false;const dates=c.evidence.map(e=>D.sources[e.source]?.published).filter(x=>/^\d{4}-\d{2}-\d{2}$/.test(x||''));return f.scope==='明确'&&(stageRanks[f.stage]||0)>=3&&stageRanks[f.stage]>(stageRanks[c.stageKey]||0)&&r.source.published>=(dates.sort().at(-1)||'');}
 function proposedLabel(c,r,f){return !f?'请先选择证据':mayUpgrade(c,r,f)?f.label:c.stage+'（新增证据，阶段保持）';}
 function sourceLink(id,page=null,custom=''){const s=D.sources[id];if(!s)return '<span class="error">来源记录缺失，暂不能复核</span>';const u=safeURL(s.url);return u?`<a target="_blank" rel="noopener noreferrer" href="${esc(u+(page?'#page='+page:''))}">${esc(custom||s.title)} ↗</a>`:'<span class="error">来源链接无效</span>';}
 const Panels=window.ResearchPanels.create(D,{esc,sourceLink});
 const Market=window.MarketPanel.create({esc,api,companies:D.companies});
 function openCompany(id){selected=id;view='companies';tab='evidence';$('search').value='';$('sector').value='all';$('scope').value='all';renderView();}
 async function api(path,body){const controller=new AbortController();const timer=setTimeout(()=>controller.abort(),60000);try{const r=await fetch('/api/'+path,{method:body?'POST':'GET',headers:body?{'Content-Type':'application/json'}:{},...(body?{body:JSON.stringify(body)}:{}),signal:controller.signal});let data;try{data=await r.json();}catch{throw Error('更新服务暂不可用，已保留当前结果。请从完整Web服务打开页面。');}if(!r.ok||data.error){const error=Error(data.error?.message||'更新暂不可用，当前结果未改变。');error.code=data.error?.code;throw error;}return data;}catch(e){if(e.name==='AbortError')throw Error('更新超时，当前结果未改变，请稍后重试。');throw e;}finally{clearTimeout(timer);}}
 function state(id){if(!states.has(id))states.set(id,{busy:false,list:null,result:null,error:'',sourceId:'',selectedFact:''});return states.get(id);}
 function renderStatus(){if(!apiStatus){$('service-state').textContent='正在连接资料更新服务';return;}$('service-state').textContent='资料更新已连接';}
 for(const name of new Set(D.companies.map(c=>c.sector))){const o=document.createElement('option');o.value=name;o.textContent=name;$('sector').appendChild(o);}
 function renderView(){
  $('company-view').hidden=view!=='companies';$('industry-view').hidden=view!=='industry';$('history-view').hidden=view!=='history';
  for(const b of document.querySelectorAll('[data-view]'))b.setAttribute('aria-pressed',String(b.dataset.view===view));
  if(view==='companies')renderList();if(view==='industry')renderIndustry();if(view==='history')renderHistory();
 }
 function renderList(){
  const q=$('search').value.trim().toLowerCase();
  const filtered=D.companies.filter(c=>(!q||[c.name,c.code,c.product,c.sector].join(' ').toLowerCase().includes(q))&&($('sector').value==='all'||c.sector===$('sector').value||c.memberships?.some(m=>D.taxonomy.nodes.find(n=>n.id===m.node)?.sector===$('sector').value))&&($('scope').value==='all'||c.relation==='明确'));
  $('result-count').textContent=`${filtered.length}家公司可查看`;
  if(!filtered.length){$('list').innerHTML='<div class="empty">没有找到这家公司。</div>';$('detail').innerHTML='<h2>暂无匹配公司</h2><p>目前收录的资料里没有匹配结果，不代表该公司没有相关业务。</p><button class="linkbutton" id="clear">清除筛选</button>';$('clear').onclick=()=>{$('search').value='';$('sector').value='all';$('scope').value='all';renderList();};return;}
  if(!filtered.some(c=>c.id===selected))selected=filtered[0].id;
  $('list').innerHTML=filtered.map(c=>`<button class="company" data-company="${esc(c.id)}" aria-pressed="${c.id===selected}"><strong>${esc(c.name)}</strong><span class="meta">${esc(c.code)} · ${esc(c.sector)}</span><span class="meta">${esc(c.stage)}</span></button>`).join('');
  for(const b of $('list').querySelectorAll('button'))b.onclick=()=>{selected=b.dataset.company;tab='evidence';renderList();};
  renderDetail();
 }
 function sourceCards(c){return c.evidence.map(ev=>{const s=D.sources[ev.source];if(!s)return '<div class="source error">来源记录缺失，暂不能复核。</div>';return `<article class="source">${sourceLink(ev.source,ev.page)}<div class="meta">${esc(s.published)} · ${ev.page?'PDF第'+ev.page+'页':esc(ev.locator||'网页正文')} · 原始披露</div>${ev.excerpt?'<blockquote>'+esc(ev.excerpt)+'</blockquote>':''}<p>${esc(ev.finding)}</p></article>`;}).join('');}
 function membership(c){return (c.memberships||[]).map(m=>{const node=D.taxonomy.nodes.find(n=>n.id===m.node);return `<div class="membership"><strong>人形机器人研究 → ${esc(node?.layer)} → ${esc(node?.name)}</strong><p>${esc(m.product)}</p><div class="meta">${esc(m.basis)} ${sourceLink(m.source,m.page,'查看判断依据')}</div></div>`;}).join('');}
 function evidencePanel(c){return `<div class="two"><div><h3 class="label">资料里已经说清楚的</h3>${lists(c.known)}</div><div class="unknown"><h3 class="label">还需要继续了解的</h3>${lists(c.unknown)}</div></div><div class="block"><h3 class="label">它在产业链中做什么</h3>${membership(c)}</div>${Panels.metrics(c)}<div class="block"><h3 class="label">这些判断从哪里来</h3>${sourceCards(c)}<div class="foot">以上依据来自公司公开披露，仍需结合完整报告和后续进展阅读。</div></div><div class="block"><h3 class="label">接下来值得关注什么</h3><p>${esc(c.next)}</p></div>`;}
 function comparisonPanel(c){const groups=D.comparisonGroups?.filter(g=>g.members.includes(c.id))||[];return groups.length?groups.map(g=>`<h3 class="label">${esc(g.title)}</h3><p>${esc(g.why)}</p><div class="table-scroll"><table><thead><tr><th>比较什么</th>${g.members.map(id=>`<th>${esc(company(id)?.name)}</th>`).join('')}</tr></thead><tbody>${g.dimensions.map(row=>`<tr><th>${esc(row.name)}</th>${g.members.map(id=>`<td>${esc(row.values[id])}</td>`).join('')}</tr>`).join('')}</tbody></table></div><p class="meta">这里使用已整理的公开资料；你个人保存的新记录不会自动更新这张比较表。</p><div class="peer-links">${g.members.map(id=>`<button class="linkbutton" data-peer="${id}">查看${esc(company(id)?.name)}证据</button>`).join('')}</div>`).join('<hr>'):`<h3 class="label">看看相似业务的公司</h3><p>${esc(c.compare)}</p><button class="linkbutton" data-peer="${esc(c.peer)}">查看${esc(company(c.peer)?.name)}证据</button><div class="notice">暂时还没有适合这家公司的海外对照。你可以到产业链页面看看“中日精密传动”或“中美整机”比较。</div>`;}
 function impactPanel(c){return Panels.impact(c,D.events.find(e=>e.id===eventId));}
 function updatePanel(c){const s=state(c.id);return `<h3 class="label">看看有没有新的资料</h3><p>先找报告，再阅读相关原文。确认有用后，可以保存到你的研究记录。</p><div class="notice">${esc(apiStatus?.mode==='model_configured'?'可以尝试用 AI 整理报告要点；保存前，请先核对原文。':'当前按关键词查找报告片段，请结合上下文阅读。')}${storeError?' '+esc(storeError):''}</div><button class="run" id="load-sources" ${s.busy?'disabled':''}>${s.busy?'正在处理…':'查找新报告'}</button>${s.error?'<p class="error" role="alert">'+esc(s.error)+'</p>':''}${s.list?`<p class="meta">${esc(s.list.coverage)}<br>查询时间：${esc(date(s.list.checkedAt))}${s.list.cached?' · 5分钟内缓存':''}</p>${s.list.sources.length?`<label class="source-select">选择要阅读的报告<select id="report-select">${s.list.sources.map(r=>`<option value="${esc(r.id)}" ${r.id===s.sourceId?'selected':''}>${esc(r.published)} · ${esc(r.title)}</option>`).join('')}</select></label><button class="linkbutton" id="analyze-report" ${s.busy?'disabled':''}>整理报告要点</button>`:'<div class="empty">当前检索范围内没有报告；这不等于没有相关业务。</div>'}`:''}${s.result?renderCandidates(c,s):''}`;}
 function renderCandidates(c,s){const r=s.result;return `<div class="block"><h3 class="label">请确认这些报告要点</h3><p class="meta">${esc(r.source.title)} · ${esc(r.source.published)}<br>${r.model.used?'本次由 AI 辅助整理，摘录已与原文核对。':'本次按关键词查找原文，未使用 AI。'}<br>读取时间：${esc(date(r.checkedAt))} · ${r.cached?'沿用最近一次读取的资料':'本次读取'}<br>${r.changed===false?'报告文件与上次一致。':r.changed===true?'报告文件有变化，请核对内容是否更新。':'这是首次读取这份资料。'} ${!r.isLatestInSearch?'注意：所选资料不是本次列表中最新报告。':''}</p><p>${esc(r.notice)}</p>${r.facts.length?`<fieldset class="candidate-list"><legend>选择一条想保存的内容</legend>${r.facts.map(f=>`<label class="candidate"><input type="radio" name="candidate" value="${esc(f.id)}" ${s.selectedFact===f.id?'checked':''}><span><span class="badge">${esc(f.label)}</span> <span class="meta">${r.source.url.toLowerCase().includes('.pdf')?'PDF第'+f.page+'页':'网页正文'}</span><blockquote>${esc(f.excerpt)}</blockquote><small>${esc(f.reason)} · ${esc(f.scope)}</small></span></label>`).join('')}</fieldset><div class="review-box"><p><strong>目前的进展：</strong>${esc(c.stage)}<br><strong>保存后：</strong><span id="proposed-stage">${esc(proposedLabel(c,r,r.facts.find(f=>f.id===s.selectedFact)))}</span></p><label class="checkline"><input type="checkbox" id="review-confirm">我已阅读原文，确认这条内容及适用范围</label><button class="run" id="apply-update" disabled>保存到我的记录</button><p class="foot">你的旧记录会保留，可以随时查看或导出。</p></div>`:''}</div>`;}
 function renderDetail(){const c=company(selected);const renderers={evidence:evidencePanel,compare:comparisonPanel,impact:impactPanel,update:updatePanel};const versions=history.filter(h=>h.companyId===c.id);$('detail').innerHTML=`<div class="heading"><div><div class="eyebrow">${esc(c.market)} / ${esc(c.code)}</div><h2>${esc(c.name)}</h2></div><span class="pill">${esc(c.sector)}</span></div><p class="product">相关产品：${esc(c.product)}</p><div class="badges"><span class="badge main">${esc(c.stage)}</span><span class="badge">人形用途：${esc(c.relation)}</span>${versions.length?'<span class="badge">我的记录 v'+versions.length+'</span>':''}</div><p class="verdict">${esc(c.verdict)}</p>${Panels.support(c)}<div class="tabs" role="tablist" aria-label="研究维度">${[['evidence','业务进展'],['compare','同业比较'],['impact','可能影响'],['update','更新资料']].map(([id,name])=>`<button class="tab" id="tab-${id}" role="tab" aria-controls="tabpanel" aria-selected="${id===tab}" data-tab="${id}">${name}</button>`).join('')}</div><div id="tabpanel" role="tabpanel" aria-labelledby="tab-${tab}">${renderers[tab](c)}</div>`;
  for(const b of $('detail').querySelectorAll('[data-tab]'))b.onclick=()=>{tab=b.dataset.tab;renderDetail();$('tab-'+tab).focus();};
  for(const b of $('detail').querySelectorAll('[data-peer]'))b.onclick=()=>openCompany(b.dataset.peer);
  bindScenario();if($('event-select'))$('event-select').onchange=e=>{eventId=e.target.value;renderDetail();};if(tab==='update')bindUpdate(c);
 }
 function bindScenario(){if(!$('scenario'))return;for(const input of $('scenario').querySelectorAll('input'))input.oninput=()=>{$('result').textContent='参数已变更，请重新计算。';$('result').className='result';};$('scenario').onsubmit=e=>{e.preventDefault();const raw=['units','value','share','realization'].map(id=>$(id).value.trim()),n=raw.map(Number),v=n[0]*n[1]*n[2]/100*n[3]/100;if(raw.some(x=>!x)||n.some(x=>!Number.isFinite(x)||x<0)||!Number.isInteger(n[0])||n[2]>100||n[3]>100||!Number.isFinite(v)){$('result').className='result error';$('result').textContent='请填写完整的非负参数；台数须为整数，比例须在0–100%之间。';return;}$('result').className='result';$('result').textContent='按你填写的假设计算：'+v.toLocaleString('zh-CN',{maximumFractionDigits:2})+' 元收入（假设）；相比全部按期交付，减少 '+(n[0]*n[1]*n[2]/100-v).toLocaleString('zh-CN',{maximumFractionDigits:2})+' 元。以上仅为假设，不是公司业绩预测。';};}
 function bindUpdate(c){const s=state(c.id);const refresh=()=>{if(selected===c.id&&tab==='update')renderDetail();};$('load-sources').onclick=async()=>{s.busy=true;s.error='';refresh();try{s.list=Guards.listing(await api('announcements?company='+encodeURIComponent(c.id)),c.id);s.sourceId=s.list.sources[0]?.id||'';s.result=null;}catch(e){s.error=e.message;}finally{s.busy=false;refresh();}};
  if($('report-select'))$('report-select').onchange=e=>{s.sourceId=e.target.value;s.result=null;refresh();};
  if($('analyze-report'))$('analyze-report').onclick=async()=>{if(!s.sourceId)return;s.busy=true;s.error='';refresh();try{const result=await api('analyze',{companyId:c.id,sourceId:s.sourceId});if(result.companyId!==c.id)throw Error('返回资料与当前公司不匹配，未改写结果。');s.result=Guards.analysis(result,c.id);s.selectedFact='';}catch(e){s.error=e.message;}finally{s.busy=false;refresh();}};
  for(const radio of document.querySelectorAll('input[name=candidate]'))radio.onchange=()=>{s.selectedFact=radio.value;$('proposed-stage').textContent=proposedLabel(c,s.result,s.result.facts.find(f=>f.id===radio.value));$('review-confirm').checked=false;$('apply-update').disabled=true;};
  if($('review-confirm'))$('review-confirm').onchange=()=>{$('apply-update').disabled=!$('review-confirm').checked||!s.selectedFact;};
  if($('apply-update'))$('apply-update').onclick=()=>applyUpdate(c,s);
 }
 function applyUpdate(c,s){const f=s.result?.facts.find(f=>f.id===s.selectedFact);if(!f||!$('review-confirm').checked)return;const source={...s.result.source,companyId:c.id,fetchedAt:s.result.checkedAt,coverage:s.result.coverage,id:s.result.source.id+'-'+s.result.source.sha256.slice(0,10)};const at=new Date().toISOString();const upgrade=mayUpgrade(c,s.result,f);const patch={stage:upgrade?f.label:c.stage,stageKey:upgrade?f.stage:c.stageKey,relation:upgrade?'明确':c.relation,verdict:upgrade?'你已复核采纳新的阶段证据。该判断属于本机研究标注，适用范围请结合原文复核。':c.verdict,known:['新采纳原文：'+f.excerpt,...c.known].slice(0,5),unknown:c.unknown,evidence:[{source:source.id,page:source.url.toLowerCase().includes('.pdf')?f.page:null,locator:'网页正文',excerpt:f.excerpt,finding:f.reason+' 用户于'+date(at)+'复核采纳。'+(upgrade?'阶段据此更新。':'作为补充证据保存，原阶段保持。')},...c.evidence].slice(0,6)};
  const version={id:at+'-'+c.id,companyId:c.id,at,from:c.stage,to:patch.stage,source,patch,engine:s.result.model.used?'AI选取+原文校验+用户复核':'规则提取+用户复核',baselineVersion:baseline.version};
  const next=[...history,version].slice(-30);try{localStorage.setItem(STORE,JSON.stringify(next));}catch{s.error='本地存储不可用，本次没有改写结果。请检查浏览器存储设置。';renderDetail();return;}history=next;Object.assign(c,patch);D.sources[source.id]=source;tab='evidence';renderList();$('global-message').textContent='已保存，你可以在“我的记录”里查看变化。';
 }
 function renderIndustry(){const nodes=D.taxonomy?.nodes||[];const layers=[...new Set(nodes.map(n=>n.layer))];$('industry-view').innerHTML=`<div class="section-title"><div><div class="eyebrow">从产业链找到感兴趣的公司</div><h2>一台机器人背后，有哪些生意？</h2></div><span class="pill">${D.companies.length}家已收录公司</span></div><p>从整机到零部件，看看不同公司负责什么，再打开它们的资料了解进展。</p><div class="chain-grid">${layers.map(layer=>`<section><h3>${esc(layer)}</h3>${nodes.filter(n=>n.layer===layer).map(n=>{const cs=D.companies.filter(c=>c.memberships?.some(m=>m.node===n.id));return `<div class="chain-node"><h4>${esc(n.name)}</h4><p>${esc(n.definition)}</p><div class="peer-links">${cs.length?cs.map(c=>`<button class="linkbutton" data-company-open="${c.id}">${esc(c.name)}</button>`).join(''):'<span class="meta">这部分公司资料还在补充</span>'}</div></div>`;}).join('')}</section>`).join('')}</div><div class="block"><div class="section-title"><h3>继续了解公司</h3><div class="peer-links"><button class="linkbutton" id="representatives" aria-pressed="true">已收录公司</button><button class="linkbutton" id="hot-list" aria-pressed="false">行情动态</button></div></div><div id="discovery-content">${representativeCards()}</div></div><div class="block"><h3>哪些变化值得留意</h3>${D.events.map(e=>`<article class="source"><span class="meta">${e.type==='hypothetical'?'假设情况 · 尚未发生':esc(e.date)+' · 已公开资料'}</span><h4>${esc(e.title)}</h4><p>${esc(e.fact)}</p>${e.source?sourceLink(e.source):''} <button class="linkbutton" data-event-open="${esc(e.id)}">看看可能的影响</button></article>`).join('')}</div>`;
  bindOpenCompanies();for(const b of document.querySelectorAll('[data-event-open]'))b.onclick=()=>{eventId=b.dataset.eventOpen;openCompany(selected);tab='impact';renderDetail();};$('representatives').onclick=()=>{$('representatives').setAttribute('aria-pressed','true');$('hot-list').setAttribute('aria-pressed','false');$('discovery-content').innerHTML=representativeCards();bindOpenCompanies();};$('hot-list').onclick=()=>{$('representatives').setAttribute('aria-pressed','false');$('hot-list').setAttribute('aria-pressed','true');Market.mount($('discovery-content'));};
 }
 function representativeCards(){return '<div class="representatives">'+D.companies.map(c=>`<button class="company" data-company-open="${c.id}"><strong>${esc(c.name)}</strong><span class="meta">${esc(c.sector)} · ${esc(c.stage)}</span><span class="meta">${esc(c.representativeReason||'研究样本')}</span></button>`).join('')+'</div>';}
 function bindOpenCompanies(){for(const b of document.querySelectorAll('[data-company-open]'))b.onclick=()=>openCompany(b.dataset.companyOpen);}
 function renderHistory(){ $('history-view').innerHTML=`<div class="section-title"><div><div class="eyebrow">把每一次新发现留下来</div><h2>我的研究记录</h2></div><button class="linkbutton" id="export-history">导出研究记录</button></div><p class="meta">记录保存在当前浏览器。换设备或清理浏览器前，记得导出一份。</p>${storeError?'<p class="error">'+esc(storeError)+'</p>':''}${history.length?[...history].reverse().map(v=>`<article class="source"><strong>${esc(company(v.companyId)?.name)} · ${esc(date(v.at))}</strong><p>${esc(v.from)} → <strong>${esc(v.to)}</strong></p><p class="meta">${esc(v.engine)} · 资料发布日期：${esc(v.source.published)}</p><p>${sourceLink(v.source.id,v.patch.evidence[0].page)}</p><button class="linkbutton" data-company-open="${v.companyId}">查看当前研究</button></article>`).join(''):'<div class="empty">还没有保存记录。选一家感兴趣的公司，在“更新资料”里查找报告，读完后保存你的第一条记录。</div>'}<div class="block"><button class="linkbutton" id="reset-history" ${history.length?'':'disabled'}>恢复初始资料</button><p class="foot">这会清除你在本浏览器保存的记录，恢复最初的资料。</p></div>`;
  bindOpenCompanies();$('export-history').onclick=()=>{const blob=new Blob([JSON.stringify({exportedAt:new Date().toISOString(),baselineVersion:baseline.version,history},null,2)],{type:'application/json'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download='robot-research-history.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};$('reset-history').onclick=()=>{if(!confirm('要清空当前浏览器的研究记录，恢复初始资料吗？建议先导出备份。'))return;try{localStorage.removeItem(STORE);}catch{}history=[];Object.assign(D,JSON.parse(JSON.stringify(baseline)));renderHistory();};
 }
 for(const b of document.querySelectorAll('[data-view]'))b.onclick=()=>{view=b.dataset.view;renderView();};
 for(const id of ['search','sector','scope'])$(id).addEventListener(id==='search'?'input':'change',renderList);
 $('sample-count').textContent=String(D.companies.length);renderStatus();renderView();
 if(typeof fetch==='function')api('status').then(s=>{apiStatus=s;renderStatus();if(tab==='update')renderDetail();}).catch(()=>{$('service-state').textContent='可以浏览资料 · 更新暂不可用';});
})();
