'use strict';
(() => {
 const D=window.RESEARCH_DATA; const Guards=window.ResearchGuards;
 if(!D?.companies?.length||!D.sources||!Guards||!window.ResearchPanels){document.getElementById('fatal').hidden=false;return;}
 const $=id=>document.getElementById(id);
 const esc=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 const safeURL=raw=>{try{const u=new URL(raw);return u.protocol==='https:'?u.href:null;}catch{return null;}};
 const lists=items=>'<ul>'+items.map(x=>'<li>'+esc(x)+'</li>').join('')+'</ul>';
 const date=iso=>{try{return new Date(iso).toLocaleString('zh-CN',{hour12:false});}catch{return iso;}};
 const baseline=JSON.parse(JSON.stringify(D));
 const states=new Map();let selected=D.companies[0].id,tab='evidence',view='companies',apiStatus=null,history=[],storeError='',eventId=D.events[0].id;
 const STORE='robot-evidence-history-v2';
 try{const stored=JSON.parse(localStorage.getItem(STORE)||'[]');if(!Array.isArray(stored))throw Error();history=stored.filter(v=>Guards.version(v)&&D.companies.some(c=>c.id===v.companyId)).slice(-30);for(const v of history){Object.assign(D.companies.find(c=>c.id===v.companyId),v.patch);D.sources[v.source.id]=v.source;}}catch{storeError='本地研究历史暂不可读，已恢复公开基线。';}
 $('app').hidden=false;
 const company=id=>D.companies.find(c=>c.id===id);
 const stageRanks={revenue:6,delivery:5,validation:4,research:3,capability:3,statement:2,insufficient:1};
 function reportPeriod(source){const t=source?.title||'';let m;if((m=t.match(/(20\d{2})年(\d{1,2})月/)))return Number(m[1])*100+Number(m[2]);if((m=t.match(/(20\d{2})年.*半年度/)))return Number(m[1])*100+6;if((m=t.match(/(20\d{2})年.*年度/)))return Number(m[1])*100+12;if((m=t.match(/Q([1-4])\s*(20\d{2})/i)))return Number(m[2])*100+Number(m[1])*3;return null;}
 function mayUpgrade(c,r,f){if(!f)return false;const incoming=reportPeriod(r.source);const prior=Math.max(0,...c.evidence.map(e=>reportPeriod(D.sources[e.source])||0));if(incoming&&prior&&incoming<prior)return false;const dates=c.evidence.map(e=>D.sources[e.source]?.published).filter(x=>/^\d{4}-\d{2}-\d{2}$/.test(x||''));return f.scope==='明确'&&(stageRanks[f.stage]||0)>=3&&stageRanks[f.stage]>(stageRanks[c.stageKey]||0)&&r.source.published>=(dates.sort().at(-1)||'');}
 function proposedLabel(c,r,f){return !f?'请先选择证据':mayUpgrade(c,r,f)?f.label:c.stage+'（新增证据，阶段保持）';}
 function sourceLink(id,page=null,custom=''){const s=D.sources[id];if(!s)return '<span class="error">来源记录缺失，暂不能复核</span>';const u=safeURL(s.url);return u?`<a target="_blank" rel="noopener noreferrer" href="${esc(u+(page?'#page='+page:''))}">${esc(custom||s.title)} ↗</a>`:'<span class="error">来源链接无效</span>';}
 const Panels=window.ResearchPanels.create(D,{esc,sourceLink});
 function openCompany(id){selected=id;view='companies';tab='evidence';$('search').value='';$('sector').value='all';$('scope').value='all';renderView();}
 async function api(path,body){const controller=new AbortController();const timer=setTimeout(()=>controller.abort(),60000);try{const r=await fetch('/api/'+path,{method:body?'POST':'GET',headers:body?{'Content-Type':'application/json'}:{},...(body?{body:JSON.stringify(body)}:{}),signal:controller.signal});let data;try{data=await r.json();}catch{throw Error('更新服务暂不可用，已保留当前结果。请从完整Web服务打开页面。');}if(!r.ok||data.error)throw Error(data.error?.message||'更新暂不可用，当前结果未改变。');return data;}catch(e){if(e.name==='AbortError')throw Error('更新超时，当前结果未改变，请稍后重试。');throw e;}finally{clearTimeout(timer);}}
 function state(id){if(!states.has(id))states.set(id,{busy:false,list:null,result:null,error:'',sourceId:'',selectedFact:''});return states.get(id);}
 function renderStatus(){if(!apiStatus){$('service-state').textContent='更新连接待确认';return;}$('service-state').textContent=apiStatus.mode==='model_configured'?'模型已配置 · 调用时验证':'公开数据更新 · 规则提取';}
 for(const name of new Set(D.companies.map(c=>c.sector))){const o=document.createElement('option');o.value=name;o.textContent=name;$('sector').appendChild(o);}
 function renderView(){
  $('company-view').hidden=view!=='companies';$('industry-view').hidden=view!=='industry';$('history-view').hidden=view!=='history';$('methods-view').hidden=view!=='methods';
  for(const b of document.querySelectorAll('[data-view]'))b.setAttribute('aria-pressed',String(b.dataset.view===view));
  if(view==='companies')renderList();if(view==='industry')renderIndustry();if(view==='history')renderHistory();if(view==='methods')$('methods-view').innerHTML=Panels.methods();
 }
 function renderList(){
  const q=$('search').value.trim().toLowerCase();
  const filtered=D.companies.filter(c=>(!q||[c.name,c.code,c.product,c.sector].join(' ').toLowerCase().includes(q))&&($('sector').value==='all'||c.sector===$('sector').value||c.memberships?.some(m=>D.taxonomy.nodes.find(n=>n.id===m.node)?.sector===$('sector').value))&&($('scope').value==='all'||c.relation==='明确'));
  $('result-count').textContent=`${filtered.length}家公司 · 研究样本顺序`;
  if(!filtered.length){$('list').innerHTML='<div class="empty">没有匹配样本。</div>';$('detail').innerHTML='<h2>暂无匹配公司</h2><p>这表示当前研究范围没有匹配结果，不代表该公司没有相关业务。</p><button class="linkbutton" id="clear">清除筛选</button>';$('clear').onclick=()=>{$('search').value='';$('sector').value='all';$('scope').value='all';renderList();};return;}
  if(!filtered.some(c=>c.id===selected))selected=filtered[0].id;
  $('list').innerHTML=filtered.map(c=>`<button class="company" data-company="${esc(c.id)}" aria-pressed="${c.id===selected}"><strong>${esc(c.name)}</strong><span class="meta">${esc(c.code)} · ${esc(c.sector)}</span><span class="meta">${esc(c.stage)}</span></button>`).join('');
  for(const b of $('list').querySelectorAll('button'))b.onclick=()=>{selected=b.dataset.company;tab='evidence';renderList();};
  renderDetail();
 }
 function sourceCards(c){return c.evidence.map(ev=>{const s=D.sources[ev.source];if(!s)return '<div class="source error">来源记录缺失，暂不能复核。</div>';return `<article class="source">${sourceLink(ev.source,ev.page)}<div class="meta">${esc(s.published)} · ${ev.page?'PDF第'+ev.page+'页':esc(ev.locator||'网页正文')} · 原始披露</div>${ev.excerpt?'<blockquote>'+esc(ev.excerpt)+'</blockquote>':''}<p>${esc(ev.finding)}</p></article>`;}).join('');}
 function membership(c){return (c.memberships||[]).map(m=>{const node=D.taxonomy.nodes.find(n=>n.id===m.node);return `<div class="membership"><strong>人形机器人研究 → ${esc(node?.layer)} → ${esc(node?.name)}</strong><p>${esc(m.product)}</p><div class="meta">${esc(m.basis)} ${sourceLink(m.source,m.page,'查看归属依据')}</div></div>`;}).join('');}
 function evidencePanel(c){return `<div class="two"><div><h3 class="label">已确认 · 限于所列证据</h3>${lists(c.known)}</div><div class="unknown"><h3 class="label">尚未确认 · 不应直接推导</h3>${lists(c.unknown)}</div></div><div class="block"><h3 class="label">产业链归属及证据</h3>${membership(c)}</div>${Panels.metrics(c)}<div class="block"><h3 class="label">原始出处与支持范围</h3>${sourceCards(c)}<div class="foot">公司原始披露支持其中的具体表述，不等于独立客户印证或审计保证。商业化阶段与来源权威性分别判断。</div></div><div class="block"><h3 class="label">下一项关键验证</h3><p>${esc(c.next)}</p></div>`;}
 function comparisonPanel(c){const groups=D.comparisonGroups?.filter(g=>g.members.includes(c.id))||[];return groups.length?groups.map(g=>`<h3 class="label">${esc(g.title)}</h3><p>${esc(g.why)}</p><div class="table-scroll"><table><thead><tr><th>比较维度</th>${g.members.map(id=>`<th>${esc(company(id)?.name)}</th>`).join('')}</tr></thead><tbody>${g.dimensions.map(row=>`<tr><th>${esc(row.name)}</th>${g.members.map(id=>`<td>${esc(row.values[id])}</td>`).join('')}</tr>`).join('')}</tbody></table></div><p class="meta">比较表引用初始证据版本；你的新采纳记录不会自动改写另一家公司或这份比较判断。</p><div class="peer-links">${g.members.map(id=>`<button class="linkbutton" data-peer="${id}">查看${esc(company(id)?.name)}证据</button>`).join('')}</div>`).join('<hr>'):`<h3 class="label">样本内业务对照</h3><p>${esc(c.compare)}</p><button class="linkbutton" data-peer="${esc(c.peer)}">查看${esc(company(c.peer)?.name)}证据</button><div class="notice">该公司暂未配置直接海外对照。可在行业页打开“中日精密传动”或“中美整机”比较组。</div>`;}
 function impactPanel(c){return Panels.impact(c,D.events.find(e=>e.id===eventId));}
 function updatePanel(c){const s=state(c.id);return `<h3 class="label">手动更新：查询 → 提取 → 复核 → 保存版本</h3><p>新材料先形成待复核证据，只有你确认后才保存到本浏览器的个人研究记录。不会覆盖公共基线或他人的研究。</p><div class="notice">${esc(apiStatus?.mode==='model_configured'?'模型接口已配置。调用成功后会标明AI选取结果，失败则明确退回规则提取。业务判断仍需复核。':'当前使用规则定位证据；未接入模型时不会标成AI分析。')}${storeError?' '+esc(storeError):''}</div><button class="run" id="load-sources" ${s.busy?'disabled':''}>${s.busy?'正在处理…':'查询最新可用报告'}</button>${s.error?'<p class="error" role="alert">'+esc(s.error)+'</p>':''}${s.list?`<p class="meta">${esc(s.list.coverage)}<br>查询时间：${esc(date(s.list.checkedAt))}${s.list.cached?' · 5分钟内缓存':''}</p>${s.list.sources.length?`<label class="source-select">选择核查材料<select id="report-select">${s.list.sources.map(r=>`<option value="${esc(r.id)}" ${r.id===s.sourceId?'selected':''}>${esc(r.published)} · ${esc(r.title)}</option>`).join('')}</select></label><button class="linkbutton" id="analyze-report" ${s.busy?'disabled':''}>读取原文并提取证据</button>`:'<div class="empty">当前检索范围内没有报告；这不等于没有相关业务。</div>'}`:''}${s.result?renderCandidates(c,s):''}`;}
 function renderCandidates(c,s){const r=s.result;return `<div class="block"><h3 class="label">待复核结果</h3><p class="meta">${esc(r.source.title)} · ${esc(r.source.published)}<br>${esc(r.model.message)}<br>读取时间：${esc(date(r.checkedAt))} · ${r.cached?'缓存结果，本次未重新请求源站或模型':'本次读取'}<br>${r.changed===false?'原文件指纹未变化。':r.changed===true?'文件指纹变化可能来自内容或技术变更，请逐项核对。':'这是新登记资料，尚无旧文件指纹可比。'} ${!r.isLatestInSearch?'注意：所选资料不是本次列表中最新报告。':''}</p><p>${esc(r.notice)}</p>${r.facts.length?`<fieldset class="candidate-list"><legend>选择一条你要纳入研究的证据</legend>${r.facts.map(f=>`<label class="candidate"><input type="radio" name="candidate" value="${esc(f.id)}" ${s.selectedFact===f.id?'checked':''}><span><span class="badge">${esc(f.label)}</span> <span class="meta">${r.source.url.toLowerCase().includes('.pdf')?'PDF第'+f.page+'页':'网页正文'}</span><blockquote>${esc(f.excerpt)}</blockquote><small>${esc(f.reason)} · ${esc(f.scope)}</small></span></label>`).join('')}</fieldset><div class="review-box"><p><strong>当前判断：</strong>${esc(c.stage)}<br><strong>采纳后：</strong><span id="proposed-stage">${esc(proposedLabel(c,r,r.facts.find(f=>f.id===s.selectedFact)))}</span></p><label class="checkline"><input type="checkbox" id="review-confirm">我已查看原文，确认仅采纳其支持的内容</label><button class="run" id="apply-update" disabled>确认并保存到我的研究</button><p class="foot">旧版本会保留，可导出或恢复。此处是用户研究标注，不是公司公告或系统认证。</p></div>`:''}</div>`;}
 function renderDetail(){const c=company(selected);const renderers={evidence:evidencePanel,compare:comparisonPanel,impact:impactPanel,update:updatePanel};const versions=history.filter(h=>h.companyId===c.id);$('detail').innerHTML=`<div class="heading"><div><div class="eyebrow">${esc(c.market)} / ${esc(c.code)}</div><h2>${esc(c.name)}</h2></div><span class="pill">${esc(c.sector)}</span></div><p class="product">核查对象：${esc(c.product)}</p><div class="badges"><span class="badge main">${esc(c.stage)}</span><span class="badge">人形关系：${esc(c.relation)}</span>${versions.length?'<span class="badge">本机研究 v'+versions.length+'</span>':''}</div><p class="verdict">${esc(c.verdict)}</p>${Panels.support(c)}<div class="tabs" role="tablist" aria-label="研究维度">${[['evidence','业务证据'],['compare','可比性'],['impact','事件传导'],['update','更新研究']].map(([id,name])=>`<button class="tab" id="tab-${id}" role="tab" aria-controls="tabpanel" aria-selected="${id===tab}" data-tab="${id}">${name}</button>`).join('')}</div><div id="tabpanel" role="tabpanel" aria-labelledby="tab-${tab}">${renderers[tab](c)}</div>`;
  for(const b of $('detail').querySelectorAll('[data-tab]'))b.onclick=()=>{tab=b.dataset.tab;renderDetail();$('tab-'+tab).focus();};
  for(const b of $('detail').querySelectorAll('[data-peer]'))b.onclick=()=>openCompany(b.dataset.peer);
  bindScenario();if($('event-select'))$('event-select').onchange=e=>{eventId=e.target.value;renderDetail();};if(tab==='update')bindUpdate(c);
 }
 function bindScenario(){if(!$('scenario'))return;for(const input of $('scenario').querySelectorAll('input'))input.oninput=()=>{$('result').textContent='参数已变更，请重新计算。';$('result').className='result';};$('scenario').onsubmit=e=>{e.preventDefault();const raw=['units','value','share','realization'].map(id=>$(id).value.trim()),n=raw.map(Number),v=n[0]*n[1]*n[2]/100*n[3]/100;if(raw.some(x=>!x)||n.some(x=>!Number.isFinite(x)||x<0)||!Number.isInteger(n[0])||n[2]>100||n[3]>100||!Number.isFinite(v)){$('result').className='result error';$('result').textContent='请填写完整的非负参数；台数须为整数，比例须在0–100%之间。';return;}$('result').className='result';$('result').textContent='假设条件全部成立时：'+v.toLocaleString('zh-CN',{maximumFractionDigits:2})+' 元收入（情景值）；相对100%兑现基准减少 '+(n[0]*n[1]*n[2]/100-v).toLocaleString('zh-CN',{maximumFractionDigits:2})+' 元（同为假设，不是公司预测）。';};}
 function bindUpdate(c){const s=state(c.id);const refresh=()=>{if(selected===c.id&&tab==='update')renderDetail();};$('load-sources').onclick=async()=>{s.busy=true;s.error='';refresh();try{s.list=Guards.listing(await api('announcements?company='+encodeURIComponent(c.id)),c.id);s.sourceId=s.list.sources[0]?.id||'';s.result=null;}catch(e){s.error=e.message;}finally{s.busy=false;refresh();}};
  if($('report-select'))$('report-select').onchange=e=>{s.sourceId=e.target.value;s.result=null;refresh();};
  if($('analyze-report'))$('analyze-report').onclick=async()=>{if(!s.sourceId)return;s.busy=true;s.error='';refresh();try{const result=await api('analyze',{companyId:c.id,sourceId:s.sourceId});if(result.companyId!==c.id)throw Error('返回资料与当前公司不匹配，未改写结果。');s.result=Guards.analysis(result,c.id);s.selectedFact='';}catch(e){s.error=e.message;}finally{s.busy=false;refresh();}};
  for(const radio of document.querySelectorAll('input[name=candidate]'))radio.onchange=()=>{s.selectedFact=radio.value;$('proposed-stage').textContent=proposedLabel(c,s.result,s.result.facts.find(f=>f.id===radio.value));$('review-confirm').checked=false;$('apply-update').disabled=true;};
  if($('review-confirm'))$('review-confirm').onchange=()=>{$('apply-update').disabled=!$('review-confirm').checked||!s.selectedFact;};
  if($('apply-update'))$('apply-update').onclick=()=>applyUpdate(c,s);
 }
 function applyUpdate(c,s){const f=s.result?.facts.find(f=>f.id===s.selectedFact);if(!f||!$('review-confirm').checked)return;const source={...s.result.source,companyId:c.id,fetchedAt:s.result.checkedAt,coverage:s.result.coverage,id:s.result.source.id+'-'+s.result.source.sha256.slice(0,10)};const at=new Date().toISOString();const upgrade=mayUpgrade(c,s.result,f);const patch={stage:upgrade?f.label:c.stage,stageKey:upgrade?f.stage:c.stageKey,relation:upgrade?'明确':c.relation,verdict:upgrade?'你已复核采纳新的阶段证据。该判断属于本机研究标注，适用范围请结合原文复核。':c.verdict,known:['新采纳原文：'+f.excerpt,...c.known].slice(0,5),unknown:c.unknown,evidence:[{source:source.id,page:source.url.toLowerCase().includes('.pdf')?f.page:null,locator:'网页正文',excerpt:f.excerpt,finding:f.reason+' 用户于'+date(at)+'复核采纳。'+(upgrade?'阶段据此更新。':'作为补充证据保存，原阶段保持。')},...c.evidence].slice(0,6)};
  const version={id:at+'-'+c.id,companyId:c.id,at,from:c.stage,to:patch.stage,source,patch,engine:s.result.model.used?'AI选取+原文校验+用户复核':'规则提取+用户复核',baselineVersion:baseline.version};
  const next=[...history,version].slice(-30);try{localStorage.setItem(STORE,JSON.stringify(next));}catch{s.error='本地存储不可用，本次没有改写结果。请检查浏览器存储设置。';renderDetail();return;}history=next;Object.assign(c,patch);D.sources[source.id]=source;tab='evidence';renderList();$('global-message').textContent='已保存本机研究版本；旧判断可在“更新记录”中查看。';
 }
 function renderIndustry(){const nodes=D.taxonomy?.nodes||[];const layers=[...new Set(nodes.map(n=>n.layer))];$('industry-view').innerHTML=`<div class="section-title"><div><div class="eyebrow">分类版本 ${esc(D.taxonomy.version)}</div><h2>从产业环节发现研究对象</h2></div><span class="pill">${D.companies.length}家样本 · 非全市场</span></div><p>${esc(D.taxonomy.definition)}</p><div class="chain-grid">${layers.map(layer=>`<section><h3>${esc(layer)}</h3>${nodes.filter(n=>n.layer===layer).map(n=>{const cs=D.companies.filter(c=>c.memberships?.some(m=>m.node===n.id));return `<div class="chain-node"><h4>${esc(n.name)}</h4><p>${esc(n.definition)}</p><div class="peer-links">${cs.length?cs.map(c=>`<button class="linkbutton" data-company-open="${c.id}">${esc(c.name)}</button>`).join(''):'<span class="meta">尚未配置公司样本</span>'}</div></div>`;}).join('')}</section>`).join('')}</div><div class="block"><div class="section-title"><h3>公司发现</h3><div class="peer-links"><button class="linkbutton" id="representatives" aria-pressed="true">产业代表</button><button class="linkbutton" id="hot-list" aria-pressed="false">市场热门</button></div></div><div id="discovery-content">${representativeCards()}</div></div><div class="block"><h3>行业事件观察</h3>${D.events.map(e=>`<article class="source"><span class="meta">${e.type==='hypothetical'?'假设情景（非已发生事实）':esc(e.date)+' · 历史披露案例'}</span><h4>${esc(e.title)}</h4><p>${esc(e.fact)}</p>${e.source?sourceLink(e.source):''} <button class="linkbutton" data-event-open="${esc(e.id)}">查看传导链</button></article>`).join('')}</div><details><summary>六档业务关系如何判断</summary><div class="grade-grid">${D.gradeDefinitions.map((g,i)=>`<div><strong>${i+1} · ${esc(g.label)}</strong><p>${esc(g.rule)}</p></div>`).join('')}</div><p>这套规则可表达所有六档。现有公司样本不为填满每一档而强行定性；“仅表态／证据不足”也在测试用例中验证。</p></details>`;
  bindOpenCompanies();for(const b of document.querySelectorAll('[data-event-open]'))b.onclick=()=>{eventId=b.dataset.eventOpen;openCompany(selected);tab='impact';renderDetail();};$('representatives').onclick=()=>{$('representatives').setAttribute('aria-pressed','true');$('hot-list').setAttribute('aria-pressed','false');$('discovery-content').innerHTML=representativeCards();bindOpenCompanies();};$('hot-list').onclick=()=>{$('representatives').setAttribute('aria-pressed','false');$('hot-list').setAttribute('aria-pressed','true');$('discovery-content').innerHTML='<div class="empty"><strong>行情数据暂未接入</strong><p>热门榜将按明确的时间窗口、成交活跃度等口径展示。当前不使用虚构涨跌幅，也不把产业代表顺序当作热度排名。</p><p class="meta">扶摇／iFinD接入后可启用。当前可通过产业代表发现公司。</p></div>';};
 }
 function representativeCards(){return '<div class="representatives">'+D.companies.map(c=>`<button class="company" data-company-open="${c.id}"><strong>${esc(c.name)}</strong><span class="meta">${esc(c.sector)} · ${esc(c.stage)}</span><span class="meta">${esc(c.representativeReason||'研究样本')}</span></button>`).join('')+'</div>';}
 function bindOpenCompanies(){for(const b of document.querySelectorAll('[data-company-open]'))b.onclick=()=>openCompany(b.dataset.companyOpen);}
 function renderHistory(){ $('history-view').innerHTML=`<div class="section-title"><div><div class="eyebrow">保留原结论，记录每次变化</div><h2>我的更新记录</h2></div><button class="linkbutton" id="export-history">导出研究记录</button></div><p class="meta">记录保存在本浏览器，属于个人研究标注。清理浏览器数据会删除记录；可先导出备份。公共基线版本：${esc(baseline.version)}。</p>${storeError?'<p class="error">'+esc(storeError)+'</p>':''}${history.length?[...history].reverse().map(v=>`<article class="source"><strong>${esc(company(v.companyId)?.name)} · ${esc(date(v.at))}</strong><p>${esc(v.from)} → <strong>${esc(v.to)}</strong></p><p class="meta">${esc(v.engine)} · 资料发布日期：${esc(v.source.published)}</p><p>${sourceLink(v.source.id,v.patch.evidence[0].page)}</p><button class="linkbutton" data-company-open="${v.companyId}">查看当前研究</button></article>`).join(''):'<div class="empty">尚无个人更新记录。打开任一公司→更新研究→查询报告→提取并复核证据，即可保存首个版本。</div>'}<div class="block"><button class="linkbutton" id="reset-history" ${history.length?'':'disabled'}>恢复公开基线</button><p class="foot">此操作仅移除本浏览器的个人标注，不改变公开资料。</p></div>`;
  bindOpenCompanies();$('export-history').onclick=()=>{const blob=new Blob([JSON.stringify({exportedAt:new Date().toISOString(),baselineVersion:baseline.version,history},null,2)],{type:'application/json'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download='robot-research-history.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};$('reset-history').onclick=()=>{if(!confirm('恢复公开基线并清空本机研究标注？建议先导出记录。'))return;try{localStorage.removeItem(STORE);}catch{}history=[];Object.assign(D,JSON.parse(JSON.stringify(baseline)));renderHistory();};
 }
 for(const b of document.querySelectorAll('[data-view]'))b.onclick=()=>{view=b.dataset.view;renderView();};
 for(const id of ['search','sector','scope'])$(id).addEventListener(id==='search'?'input':'change',renderList);
 $('sample-count').textContent=String(D.companies.length);renderStatus();renderView();
 if(typeof fetch==='function')api('status').then(s=>{apiStatus=s;renderStatus();if(tab==='update')renderDetail();}).catch(()=>{$('service-state').textContent='证据可浏览 · 更新服务未连接';});
})();
