(() => {
 function create(D,{esc,sourceLink}){
  const number=v=>Number(v).toLocaleString('zh-CN',{maximumFractionDigits:6});
  function metrics(c){const rows=c.metrics||[];return `<div class="block"><h3 class="label">重要数字，看清范围和出处</h3>${rows.length?`<div class="table-scroll"><table><thead><tr><th>指标和金额</th><th>统计范围和时间</th><th>出处及单位换算</th></tr></thead><tbody>${rows.map(m=>`<tr><td><strong>${esc(m.name)}</strong><br>${m.approximate?'约':''}${number(m.reportedValue)} ${esc(m.reportedUnit)}</td><td>${esc(m.scope)}<br><span class="meta">${esc(m.period)}</span></td><td>${sourceLink(m.source,m.page,'原文第'+m.page+'页')}<br>${m.multiplier===1?'保持原单位':`${number(m.reportedValue)} × ${number(m.multiplier)} = ${number(m.value)} ${esc(m.unit)}`}<br><span class="meta">${esc(m.qualification)}</span></td></tr>`).join('')}</tbody></table></div>`:'<p class="meta">目前还没有找到单独列出的人形机器人收入，不能用公司总收入代替。</p>'}</div>`;}
  const supportText = value => ({'直接支持所列阶段':'报告写明了上面的业务进展。','直接支持部分产品交付；客户与用途需细化':'部分产品已交付，但客户和具体用途还不清楚。','部分支持；人形用途或范围待核':'已有相关业务，但还不能确认哪些用于人形机器人。','直接支持供货能力；不支持已实际交付':'可以确认具备供货能力，尚未确认实际交付。','直接支持历史研发活动；当前进度待补证':'可以确认此前的研发活动，还需查找最新进展。'}[value] || value || '这条个人记录还需要持续确认');
  function support(c){return `<p class="evidence-support"><strong>资料能说明什么：</strong>${esc(supportText(c.evidenceAssessment?.support))}</p>`;}
  function impact(c,event){const e=event||D.events[0];const path=e.companyPaths?.find(x=>x.companyId===c.id);return `<label class="source-select">想了解哪件事的影响？<select id="event-select">${D.events.map(x=>`<option value="${esc(x.id)}" ${x.id===e.id?'selected':''}>${esc(x.category)} · ${esc(x.title)}${x.type==='hypothetical'?'（假设）':''}</option>`).join('')}</select></label><div class="eyebrow">${e.type==='hypothetical'?'假设情况 · 尚未发生':'公开资料 · '+esc(e.date)}</div><h3>${esc(e.title)}</h3><p>${esc(e.fact)}</p>${e.source?`<p>${sourceLink(e.source,null,'查看事件原始出处')} <span class="meta">${esc(e.locator)}</span></p>`:'<p class="meta">这是用于观察风险的假设，不是已经发生的新闻。</p>'}<div class="path">${e.steps.map((s,i)=>`<div class="node"><b>${i+1} · ${esc(s.title)} <span class="badge">${esc(s.kind)}</span></b><p>${esc(s.detail)}</p></div>`).join('')}</div>${path?`<div class="block"><h3 class="label">对 ${esc(c.name)} 可能有什么影响？</h3><p><strong>先影响：</strong>${esc(path.firstHit)}<br><strong>对应业务：</strong>${esc(path.business)}</p><div class="notice"><strong>先要确认：</strong>${esc(path.relationshipGate)}</div><p class="meta">相关业务的出处：${path.basis.map(s=>sourceLink(s.source,s.page)).join('；')}。材料说明公司有这些业务，但不代表已经与事件中的企业合作。</p><div class="table-scroll"><table><thead><tr><th>财务指标</th><th>可能怎么变</th><th>为什么会变化</th><th>还需要确认什么</th></tr></thead><tbody>${path.financial.map(x=>`<tr><th>${esc(x.indicator)}</th><td>${esc(x.direction)}</td><td>${esc(x.mechanism)}</td><td>${esc(x.unknown)}</td></tr>`).join('')}</tbody></table></div><p class="foot">${esc(path.kind)}。资料还不完整，暂不能估计利润会增加多少。</p></div>`:'<div class="notice">目前还没有足够资料判断这件事对公司的影响。</div>'}<div class="block"><h3 class="label">换一组数字，看看收入可能差多少</h3><p class="meta">你可以填写自己的假设进行计算。单机金额是一台机器人使用这些部件的总价；结果不是公司业绩预测。</p><form id="scenario" novalidate><div class="fields">${[['units','假设机器人数量（台）'],['value','单机部件金额（元）'],['share','这家公司供应的份额（%）'],['realization','当期实际交付比例（%）']].map(([id,label])=>`<label>${label}<input id="${id}" type="number" min="0" ${['share','realization'].includes(id)?'max="100"':''} step="${id==='units'?'1':'any'}" placeholder="待输入"></label>`).join('')}</div><button class="run" type="submit">计算假设收入</button><div class="result" id="result" aria-live="polite">填好上面的数字，再看看结果。</div></form><p class="foot">计算方式：数量 × 单机金额 × 供应份额 × 交付比例。实际订单和确认收入的时间仍需查证。</p></div>`;}
  return {metrics,support,impact};
 }
 (typeof window==='undefined'?globalThis:window).ResearchPanels={create};
})();
