(() => {
 function create(D,{esc,sourceLink}){
  const number=v=>Number(v).toLocaleString('zh-CN',{maximumFractionDigits:6});
  function metrics(c){const rows=c.metrics||[];return `<div class="block"><h3 class="label">关键数字及口径追溯</h3>${rows.length?`<div class="table-scroll"><table><thead><tr><th>指标与原始数字</th><th>范围与报告期</th><th>出处与换算</th></tr></thead><tbody>${rows.map(m=>`<tr><td><strong>${esc(m.name)}</strong><br>${m.approximate?'约':''}${number(m.reportedValue)} ${esc(m.reportedUnit)}</td><td>${esc(m.scope)}<br><span class="meta">${esc(m.period)}</span></td><td>${sourceLink(m.source,m.page,'原文第'+m.page+'页')}<br>${m.multiplier===1?'保持原单位':`${number(m.reportedValue)} × ${number(m.multiplier)} = ${number(m.value)} ${esc(m.unit)}`}<br><span class="meta">${esc(m.qualification)}</span></td></tr>`).join('')}</tbody></table></div>`:'<p class="meta">本轮材料未建立可单列的人形业务收入金额，保持未知，不填0。公司整体收入也不替代该业务收入。</p>'}</div>`;}
  function support(c){return `<p class="evidence-support"><strong>证据支持：</strong>${esc(c.evidenceAssessment?.support||'使用者研究标注，待持续复核')}<br><span class="meta">${esc(c.evidenceAssessment?.basis||'不是独立审计或客户确认。')}</span></p>`;}
  function impact(c,event){const e=event||D.events[0];const path=e.companyPaths?.find(x=>x.companyId===c.id);return `<label class="source-select">选择外部变化<select id="event-select">${D.events.map(x=>`<option value="${esc(x.id)}" ${x.id===e.id?'selected':''}>${esc(x.category)} · ${esc(x.title)}${x.type==='hypothetical'?'（假设）':''}</option>`).join('')}</select></label><div class="eyebrow">${e.type==='hypothetical'?'假设情景 · 非已发生新闻':'真实历史披露 · '+esc(e.date)}</div><h3>${esc(e.title)}</h3><p>${esc(e.fact)}</p>${e.source?`<p>${sourceLink(e.source,null,'查看事件原始出处')} <span class="meta">${esc(e.locator)}</span></p>`:'<p class="meta">无新闻来源：此项用于检验下行压力，不能当作当前公司事实。</p>'}<div class="path">${e.steps.map((s,i)=>`<div class="node"><b>${i+1} · ${esc(s.title)} <span class="badge">${esc(s.kind)}</span></b><p>${esc(s.detail)}</p></div>`).join('')}</div>${path?`<div class="block"><h3 class="label">落实到 ${esc(c.name)} 的业务与财务</h3><p><strong>先影响：</strong>${esc(path.firstHit)}<br><strong>对应业务：</strong>${esc(path.business)}</p><div class="notice"><strong>关键条件／断点：</strong>${esc(path.relationshipGate)}</div><p class="meta">产品归属依据：${path.basis.map(s=>sourceLink(s.source,s.page)).join('；')}。这些来源证明产品或业务活动，不自动证明该外部事件与公司有商业关系。</p><div class="table-scroll"><table><thead><tr><th>财务指标</th><th>可能方向</th><th>具体传导</th><th>缺少的证据</th></tr></thead><tbody>${path.financial.map(x=>`<tr><th>${esc(x.indicator)}</th><td>${esc(x.direction)}</td><td>${esc(x.mechanism)}</td><td>${esc(x.unknown)}</td></tr>`).join('')}</tbody></table></div><p class="foot">${esc(path.kind)}。未知参数不填零，不自动给出盈利增厚。</p></div>`:'<div class="notice">该公司尚未建立完整传导路径，不输出受益判断。</div>'}<div class="block"><h3 class="label">假设演算 · 不绑定公司业绩</h3><p class="meta">以下数值全部由使用者输入，不是新闻数字或模型预测。单机金额指一台整机所需对应部件的总额。</p><form id="scenario" novalidate><div class="fields">${[['units','假设整机数量（台）'],['value','单机部件金额（元）'],['share','供应份额（%）'],['realization','当期交付兑现比例（%）']].map(([id,label])=>`<label>${label}<input id="${id}" type="number" min="0" ${['share','realization'].includes(id)?'max="100"':''} step="${id==='units'?'1':'any'}" placeholder="待输入"></label>`).join('')}</div><button class="run" type="submit">计算假设收入</button><div class="result" id="result" aria-live="polite">参数未齐，不生成估算。</div></form><p class="foot">数量 × 单机金额 × 份额 × 兑现比例；不构成投资建议。实际订单、供应关系和会计期间仍需另证。</p></div>`;}
  function methods(){const m=D.methodology;return `<div class="section-title"><div><div class="eyebrow">研究方法与合规边界</div><h2>事实、假设和未知项分别呈现</h2></div></div><div class="notice"><strong>${esc(m.disclaimer)}</strong> 不提供买卖建议或收益保证。</div><h3>业务实质分级与证据支持分开</h3><p>分级回答业务做到哪一步；证据支持回答原文能证明多少。正式公告中的计划仍是计划，不能因为来源正式就升级为收入。</p><div class="grade-grid">${D.gradeDefinitions.map((g,i)=>`<div><strong>${i+1} · ${esc(g.label)}</strong><p>${esc(g.rule)}</p></div>`).join('')}</div><p class="meta">供货能力不是已交付；明确否认、仅表态和检索范围内证据不足分别记录。当前真实公司样本不为填满六档而强行定性。</p><div class="block"><h3>AI、程序与使用者分别做什么</h3><div class="table-scroll"><table><thead><tr><th>角色</th><th>职责</th><th>边界</th></tr></thead><tbody>${m.aiRoles.map(r=>`<tr><th>${esc(r.actor)}</th><td>${esc(r.does)}</td><td>${esc(r.doesNot)}</td></tr>`).join('')}</tbody></table></div><p>每次提取结果标明实际使用AI还是规则降级。模型输出不通过原文包含校验时，拒绝采纳；新证据必须复核后才能进入个人版本。</p></div><div class="block"><h3>这些结论不能直接说</h3><div class="table-scroll"><table><thead><tr><th>错误推断示例</th><th>应如何表达</th></tr></thead><tbody>${m.boundaries.map(x=>`<tr><td>❌ ${esc(x.bad)}</td><td>${esc(x.correct)}</td></tr>`).join('')}</tbody></table></div></div><div class="block"><h3>数据源挂了怎么办</h3><p>明确显示超时、限流、格式变化或访问拒绝；保留旧研究及原出处，不将失败包装成“无业务”。缓存会显示缓存状态与查询时间。模型失败时标明规则模式；证据字段不完整时禁止采纳。</p><p><a href="测试说明.md" target="_blank" rel="noopener">查看已执行的故障与合规测试</a></p></div><div class="block"><h3>未做和拿不到的数据</h3><ul>${m.unknowns.map(x=>'<li>'+esc(x)+'</li>').join('')}</ul></div>`;}
  return {metrics,support,impact,methods};
 }
 (typeof window==='undefined'?globalThis:window).ResearchPanels={create};
})();
